### ISSUE TITLE
Size of usb?

### ISSUE THREAD

**Issue by WgpArch** [sashwatsamaddar/arch-install#1]

**Comment by sashwatsamaddar** [comment]
Hi,
This repo just a set of instructions for personal use while installing Arch from the terminal so that I don't have to open Arch wiki. 

It's not meant to be used as an install script. You can find much better install scripts on GitHub if you are having trouble with the instructions on Arch wiki

**Comment by WgpArch** [comment]
I just aked for the size of the usb amd really tried it and use it as script,I type commamds but the grub installl did not work,neither did the ome on the wiki.

**Comment by WgpArch** [comment]
Hi can we chat on telegram signal or whatsapp I have issues ans tried various ways and it still does not work. I teies your install the wiki one also and did not work. I tried this but it too does not work.
https://mags.zone/help/arch-usb.html#partition
⁣Get BlueMail for Android ​

**Comment by sashwatsamaddar** [comment]
I think I used a 128GB Samsung USB drive.

As for the grub install, there are many factors to keep in mind. The command used here is for a UEFI system with efi partition mounted to /efi

I would recommend the following -
1. Check if your system is UEFI or Legacy BIOS
2. Make sure your drive partition scheme is proper - GPT for UEFI and MBR for BIOS
3. Provide the correct efi partition in grub command

If you are having trouble, you can post your particular query on reddit.com/r/archlinux
Reddit folks may be able to help you better

**Comment by WgpArch** [comment]
Ok will retry will it be an issue my usb is 32GB

⁣Get BlueMail for Android ​
